#!/usr/bin/env bash
# displays 'To infinity and beyond' indefinitely while handling several Signals
trap hate_and_remove SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/holbertonscript.pid; exit' SIGQUIT
hate_and_remove()
{
	echo "I hate the kill command"
	rm /var/run/holbertonscript.pid
	exit
}
echo $$ > /var/run/holbertonscript.pid
while :
do
	echo 'To infinity and beyond'
	sleep 2
done
