#!/usr/bin/env bash
# pings an IP address passed as an argument
ip_address=$1
if [ "$ip_address" = "" ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit
fi
ping -c 5 "$ip_address"
