#!/usr/bin/env bash
#transfer a file to your server
FILE=$1
IP=$2
USERNAME=$3
KEY_PATH=$4
if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$KEY_PATH" -o "StrictHostKeyChecking=no" "$FILE" "$USERNAME@$IP":~/
fi
