#!/usr/bin/env bash
#install nginx on web server
sudo apt-get update
sudo apt-get -y install nginx
sudo cp /usr/share/nginx/html/index.html /usr/share/nginx/html/init_index.html
sudo su
echo "Holberton School for the win!" > /usr/share/nginx/html/index.html
sudo service nginx start
