#!/usr/bin/env bash
# configure nginx server so /redirect_me is redirecting to another page
sudo apt-get update
sudo apt-get -y install nginx
REDIRECT='location /redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n}\n'
sudo sed -i "30i $REDIRECT" /etc/nginx/sites-available/default
sudo service nginx restart
