#!/usr/bin/env bash
# configure nginx server to have custom 404 page
sudo apt-get update
sudo apt-get -y install nginx
REDIRECT='location /redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n}\n'
sudo sed -i "30i $REDIRECT" /etc/nginx/sites-available/default


#create custom 404 page
old_str='#error_page 404 \/404.html;'
replace_str='error_page 404 \/custom_404.html;'
sudo sed -i "s/$old_str/$replace_str/" /etc/nginx/sites-available/default

sudo touch /usr/share/nginx/html/custom_404.html
sudo echo -e "Ceci n'est pas une page\n" | sudo tee /usr/share/nginx/html/custom_404.html

sudo service nginx restart
