#!/usr/bin/env bash
#modifies localhost and adds 8.8.8.8 facebook.com to /etc/hosts
cp /etc/hosts ~/hosts.new
sed -i.bak '/localhost/d' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
echo "127.0.0.2 localhost" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
